title: SudanJUG
email: sudanjug@gmail.com
description: >-
  Sudan Java User Group (SudanJUG).
baseurl: "/"
url: "https://sudanjug.github.io"
twitter_username: SudanJUG
github_username:  SudanJUG

theme: minima
#plugins:
#  - jekyll-feed

